// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdf6WXOLHhEIq2hP4J1yzcIWSyCXkd1Lk',
    appId: '1:229856571443:web:629f33727e7d02e52df346',
    messagingSenderId: '229856571443',
    projectId: 'trabalho-final-flutter-mobile',
    authDomain: 'trabalho-final-flutter-mobile.firebaseapp.com',
    storageBucket: 'trabalho-final-flutter-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxceP-e3I6PNH9WXXCpVr3AGSrDjloKY0',
    appId: '1:229856571443:android:37f846de531cb5d42df346',
    messagingSenderId: '229856571443',
    projectId: 'trabalho-final-flutter-mobile',
    storageBucket: 'trabalho-final-flutter-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdv1alEjrijMCR4hK7qmXl1w9g9z5Azy4',
    appId: '1:229856571443:ios:fdd910132b8fe6462df346',
    messagingSenderId: '229856571443',
    projectId: 'trabalho-final-flutter-mobile',
    storageBucket: 'trabalho-final-flutter-mobile.appspot.com',
    iosBundleId: 'com.example.trabalhoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdv1alEjrijMCR4hK7qmXl1w9g9z5Azy4',
    appId: '1:229856571443:ios:1da58e9a1e4f2f262df346',
    messagingSenderId: '229856571443',
    projectId: 'trabalho-final-flutter-mobile',
    storageBucket: 'trabalho-final-flutter-mobile.appspot.com',
    iosBundleId: 'com.example.trabalhoFinal.RunnerTests',
  );
}
